# -*- mode: ruby -*-
# vi: set ft=ruby :

## Vagrant :: Ubuntu 14.04 + MongoDB 2.6 :: Vagrant File ##

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    config.vm.box = "ubuntu/trusty64"
    config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
    # VM config
    config.vm.define :mongodb do |mongodb|
        mongodb.vm.network :private_network, ip: "10.11.12.13"
        mongodb.vm.network :forwarded_port, host: 27017, guest: 27017

        mongodb.vm.hostname = "mongodb"

        mongodb.vm.provider 'virtualbox' do |v|
            v.customize ['modifyvm', :id, '--name', 'ubuntu1404-mongodb32']
            v.customize ['modifyvm', :id, '--cpus', '1']
            v.customize ['modifyvm', :id, '--memory', 1024]
            v.customize ['modifyvm', :id, '--ioapic', 'off']
            v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
            v.customize ['modifyvm', :id, '--nictype1', 'virtio']
            v.customize ['modifyvm', :id, '--nictype2', 'virtio']
        end

        # Basic box provisioning
        mongodb.vm.provision "shell", path: "provision.sh"

        # Fixing missing tty
		mongodb.vm.provision "fix-no-tty", type: "shell" do |s|
				s.privileged = false
				s.inline = "sudo sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
		end

		# MongoDB initialization JS script
		mongodb.vm.provision "file", source: "initial.js", destination: "initial.js"

		# MongoDB provisioning
		mongodb.vm.provision "shell", path: "mongodb_provision.sh"
    end
end
